# http
POST http://localhost:4000/api/wilders HTTP/1.1
content-type: application/json

{
    "name":"Http Wilder",
    "city": "Londres",
    "skills":[
        {"title":"express", "votes":5},
        {"title":"mongo", "votes":12}
    ]
}

###

PUT http://localhost:4000/api/wilders/Http Wilder HTTP/1.1
content-type: application/json

{
    "city": "Paris",
    "skills":[
        {"title":"express", "votes":8},
        {"title":"mongo", "votes":42}
    ]
}

###

DELETE  http://localhost:4000/api/wilders/Http Wilder HTTP/1.1
content-type: application/json

###

GET http://localhost:4000/api/wilders HTTP/1.1